"""Add 1o1 relation Promo-Cart

Revision ID: 04b24c092f77
Revises: 08ae0e1f24c1
Create Date: 2025-12-15 16:10:50.503561

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '04b24c092f77'
down_revision = '08ae0e1f24c1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('promo', 'discount_value',
               existing_type=sa.NUMERIC(precision=6, scale=2),
               nullable=True)
    op.alter_column('promo', 'discount_type',
               existing_type=postgresql.ENUM('PERCENT', 'FIXED', name='discounttype'),
               nullable=True)
    op.alter_column('promo', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('promo', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('promo', 'discount_type',
               existing_type=postgresql.ENUM('PERCENT', 'FIXED', name='discounttype'),
               nullable=False)
    op.alter_column('promo', 'discount_value',
               existing_type=sa.NUMERIC(precision=6, scale=2),
               nullable=False)
    # ### end Alembic commands ###
