"""Add Promo, Cart and Cart model

Revision ID: 08ae0e1f24c1
Revises: 
Create Date: 2025-10-20 20:24:45.308340

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '08ae0e1f24c1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('promo',
    sa.Column('code', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('discount_value', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('discount_type', sa.Enum('PERCENT', 'FIXED', name='discounttype'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_promo_code'), 'promo', ['code'], unique=False)
    op.create_table('cart',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('total_price', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('promo_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['promo_id'], ['promo.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('order',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('promo_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['promo_id'], ['promo.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('order')
    op.drop_table('cart')
    op.drop_index(op.f('ix_promo_code'), table_name='promo')
    op.drop_table('promo')
    # ### end Alembic commands ###
