name: Test Docker Compose

on:
  push:
    branches:
      - master
  pull_request:
    types:
      - opened
      - synchronize

jobs:

  test-docker-compose:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Create .env file for Docker Compose
        run: |
          echo "SECRET_KEY=${{ secrets.SECRET_KEY }}" >> .env
          echo "FIRST_SUPERUSER=${{ secrets.FIRST_SUPERUSER }}" >> .env
          echo "FIRST_SUPERUSER_PASSWORD=${{ secrets.FIRST_SUPERUSER_PASSWORD }}" >> .env
          echo "POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }}" >> .env
          echo "POSTGRES_USER=${{ secrets.POSTGRES_USER }}" >> .env
          echo "POSTGRES_DB=${{ secrets.POSTGRES_DB }}" >> .env
          echo "DOMAIN=localhost" >> .env
          echo "ENVIRONMENT=local" >> .env
          echo "STACK_NAME=basuketto" >> .env
          echo "BACKEND_CORS_ORIGINS=http://localhost" >> .env
          echo "EMAILS_FROM_EMAIL=test@example.com" >> .env
          echo "POSTGRES_PORT=5432" >> .env
          echo "SENTRY_DSN=" >> .env
          echo "STACK_NAME=basuketto" >> .env
          echo "DOCKER_IMAGE_BACKEND=basuketto-backend:latest" >> .env
      - run: docker compose build
      - run: docker compose down -v --remove-orphans
      - run: docker compose up -d --wait backend adminer
      - name: Test backend is up
        run: curl http://localhost:8000/api/v1/utils/health-check
      - run: docker compose down -v --remove-orphans
